# Dependabot configuration for automated dependency updates
# 
# This configuration creates consolidated PRs with ALL dependency updates
# to significantly reduce notification noise while keeping dependencies current.
#
# Changes from original configuration:
# - Groups ALL npm dependencies into one single PR (was ~10 individual PRs)
# - Groups ALL GitHub Actions into one single PR (was ~5 individual PRs)  
# - Reduces total from 15+ individual PRs per week to 2 grouped PRs per week
# - Schedules both updates on the same day for easier management
# - Achieves the core goal of "one PR with all changes" per ecosystem
#
# Bi-weekly scheduling:
# While Dependabot doesn't directly support bi-weekly intervals, this configuration
# significantly reduces PR noise. To achieve approximately bi-weekly updates:
# - The grouped PRs will only be created when there are actual updates available
# - With open-pull-requests-limit: 1, no new PRs are created until existing ones are handled
# - This naturally creates a more spaced-out update rhythm
#
# Usage:
# - Dependabot creates grouped PRs with all available updates for each ecosystem
# - PRs are labeled "npm" or "github-actions" for categorization
# - Major version updates are ignored to prevent breaking changes
# - Manual review is recommended for security updates
#
# For more information: https://docs.github.com/en/code-security/dependabot

version: 2
updates:
  # All NPM dependencies grouped into single weekly PR
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 1
    reviewers:
      - "blackwhitehere"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "npm"
    ignore:
      # Ignore major version updates for breaking changes
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      npm-dependencies:
        patterns:
          - "*"
        
  # All GitHub Actions grouped into single weekly PR
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "10:30"
    open-pull-requests-limit: 1
    reviewers:
      - "blackwhitehere"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "github-actions"
    groups:
      github-actions:
        patterns:
          - "*"
