# Documentation Build and Deploy Pipeline
#
# This workflow builds and deploys documentation to GitHub Pages using MkDocs Material.
# It runs when documentation files are changed or can be triggered manually.
#
# Features:
# - Automatic building of MkDocs documentation
# - Deployment to GitHub Pages
# - Python environment setup for MkDocs
# - Material theme with modern styling
#
# Usage:
# - Automatically triggered on pushes to main that change docs/ files or mkdocs.yml
# - Can be manually triggered via workflow_dispatch
# - Documentation is deployed to: https://blackwhitehere.github.io/acme-portal/
#
# Requirements:
# - GitHub Pages must be enabled in repository settings
# - Set Pages source to "GitHub Actions" in repository settings

name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install MkDocs and dependencies
        run: |
          pip install mkdocs-material
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Build documentation
        run: mkdocs build
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4